[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.6.4"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"
